### PR TITLE
u-boot: fix the issue that board can't load the correct dtb

### PR DESCRIPTION
**Pull request by AsuraZeng**
the name like k3-am6528-iot2050-basic-pg2 not the iot2050-basic-pg2.
so it can't find the correnct dtb.

correct this issue

Signed-off-by: chao zeng <chao.zeng@siemens.com>

### CODE REVIEW

**Comment by jan-kiszka** [comment]
Let me check the causing commit, and then we will fix that one up. No need for stacking things.

**Comment by AsuraZeng** [comment]
> Let me check the causing commit, and then we will fix that one up. No need for stacking things.

this original commit has already upstream,not int the currently patches list.

**Comment by jan-kiszka** [comment]
Unlikely - we added support for PG2 and tested that before upstreaming it.

**Comment by AsuraZeng** [comment]
this is a new bug introduced after the commit 5ac8edaca2fd29c87c2bd4922b464b31a6dbd674.
and this bug is caused by using the fdt-SEQ.

**Comment by jan-kiszka** [comment]
NACK: I've just built the image for PG2 via master and tested it on PG2 Basic. It's all fine. I suspect you accidentally built for PG1.

**Comment by jan-kiszka** [comment]
OK, reproduced now: We better cut off that new prefix which confuses the match. strstr could eventually stumble over "name" vs. "name-suffix". The fix should go into the causing commit (https://github.com/siemens/u-boot/commit/5cf7130b85e9e76ffee765aabb56a972fbe050ed). I'll update the queues.

**Comment by AsuraZeng** [comment]
> OK, reproduced now: We better cut off that new prefix which confuses the match. strstr could eventually stumble over "name" vs. "name-suffix". The fix should go into the causing commit ([siemens/u-boot@5cf7130](https://github.com/siemens/u-boot/commit/5cf7130b85e9e76ffee765aabb56a972fbe050ed)). I'll update the queues.

Ok, I  agree. I would drop this PR.

**Pull request closed without merging**
