### PR TITLE
Update tiboot3.bin and sysfw

### PR DESCRIPTION
**Pull request by BaochengSu**
Update tiboot3.bin to D01.01.00.01

Update sysfw to 2021.05

### CODE REVIEW

**Comment by BaochengSu** [comment]
This one should be merged after SR2 kernel ready

**Comment by jan-kiszka** [comment]
Why only then? Does it break anything for the current kernel?

**Comment by jan-kiszka** [comment]
And please also already queue pru firmware updates / extensions. Something like https://github.com/siemens/meta-iot2050/commit/836dd17108070b87a0fbfacccfb7ae10814c6fd6 (plus the links in recipes-bsp/u-boot/files/prebuild/).

**Comment by BaochengSu** [comment]
> Why only then? Does it break anything for the current kernel?

Sorry, that's a mistake.

**Comment by BaochengSu** [comment]
> And please also already queue pru firmware updates / extensions. Something like [836dd17](https://github.com/siemens/meta-iot2050/commit/836dd17108070b87a0fbfacccfb7ae10814c6fd6) (plus the links in recipes-bsp/u-boot/files/prebuild/).

Done.

**Comment by jan-kiszka** [comment]
Too late for this round, but maybe we can rather pick the binary from https://git.ti.com/cgit/processor-firmware/ti-linux-firmware/tree/ti-pruss?h=ti-linux-firmware. Theoretically, the same versions should be available there as well.

**Pull request merged**
