### PR TITLE
HACK: tty: Flush any pending characters in the driver

### PR DESCRIPTION
**Pull request by AsuraZeng**
omap_8250 can't send the data when closing the port,it keeps the buffer.

then re-used the port, at least there are several bugs.
1. the receive side could receive these data again.
2. it would hang when change the termios.

Flush the buffer when send timeout or some errors.

Signed-off-by: chao zeng <chao.zeng@siemens.com>

### CODE REVIEW

**Comment by AsuraZeng** [comment]
I think this should be upstream too. When the sending fails, the output buffer needs empty, to enhance the flow of robust

**Comment by jan-kiszka** [comment]
So, #211 was basically a symptom of what this tries to resolve.

Questions:
- Is this behavior different to an older kernel version? Or our old BSP kernel?
- Is this really generic (you patch generic code)? Or rather omap-specific as your comment above suggests?

**Comment by AsuraZeng** [comment]
yes , #211  is just one of the symptoms. 

Questions:

    Is this behavior different to an older kernel version? Or our old BSP kernel?
     yes ,it is different with older kernel version. 
    Is this really generic (you patch generic code)? Or rather omap-specific as your comment above suggests?
    yes,this is generic code,not the omap specific code. I observed several other uart devices and found that the final buffers were all emptied. maybe this is a common behavior,buffer will be emptied anyway.When sending timeout or abnormal then empty the buffer.

**Comment by jan-kiszka** [comment]
Can you specify the kernel versions that used to work?

And, no, the problem is NOT generic when it only affects the OMAP UART, and all others do that clearing anyway. In that case, the patch must target the driver, not the tty layer.

**Comment by AsuraZeng** [comment]
Currently , I found kernel 4.19.94 works fine.

Yes,actually this should target to omap driver. For tty layer is just a workaround.

**Comment by jan-kiszka** [comment]
Not a bug of the kernel, wrong test pattern: close() as well as TCSETSW (what stty uses) shall block until pending transmissions are flushed. If those can't make progress due to remote side not accepting them, the application must flush the buffers first - or use TCSETS.

**Comment by AsuraZeng** [comment]
if so, #211   needs to re-open and patch to our currently  mraa.

**Comment by jan-kiszka** [comment]
Yes, we need a patch to mraa, but not like #211. And not only there.

We need a new function in mraa in order to drop the output buffer, and that needs to be called explicitly from the application. As `mraa_uart_flush()` is already defined for draining output, a new `mraa_uart_clear()` could serve for dropping queues, maybe with a parameter to select input/output/both.

**Comment by jan-kiszka** [comment]
And mraa API changes needs to be discussed upstream first, to avoid that we invent something that then becomes IOT2050-only.

**Pull request closed without merging**
