### PR TITLE
Su/hw reset cp210x

### PR DESCRIPTION
**Pull request by BaochengSu**
Add the hardware reset to the CP210X, origined from Chao.

### CODE REVIEW

**Comment by jan-kiszka** [comment]
Does this address the rs485 issue you mentioned? Or which scenario does it resolve?

**Review by AsuraZeng — APPROVED** [review]

**Comment by AsuraZeng** [comment]
@jan-kiszka  it could no need to reboot the device  making  change the com port function among 232 485 422 take effect for PG2 board

**Comment by AsuraZeng** [comment]
@BaochengSu  lack of  supporting for the `CP2102N-RESET` pin.
pls refer https://github.com/siemens/meta-iot2050/commit/20d582b03da29fa1e11429c9d18465cfe2a9768a
`main_gpio1` dts node to pick the `CP2102N-RESET` related setting

**Comment by BaochengSu** [comment]
> Does this address the rs485 issue you mentioned? Or which scenario does it resolve?

RS485 issue is another topic. This one is regarding of the CP210x hardware design change for PG2.

Under the new design, it's not necessory to reboot the board to let the serial switching taking effect.

**Pull request merged**
