### PR TITLE
dts: reconfigure pcie node

### PR DESCRIPTION
**Pull request by AsuraZeng**
as lack of property:num-lanes,there is no any phy link,the board can not
detect pcie devices.

Signed-off-by: Chao Zeng <chao.zeng@siemens.com>

### CODE REVIEW

**Comment by jan-kiszka** [comment]
Maybe just refresh that queue to https://git.kernel.org/pub/scm/linux/kernel/git/soc/soc.git/commit/arch/arm64/boot/dts/ti/k3-am65-iot2050-common.dtsi?h=for-next&id=e180f76d06412bb412ab675dadeb8c2b64da1dcf and related commits? Make sure to track upstream via backports from no on, prepare own patches to be ready for upstream submission.

**Comment by BaochengSu** [comment]
@jan-kiszka this is targeted on SR2 branch :)

**Comment by jan-kiszka** [comment]
Yes, and it would be time to align that branch to upcoming upstream baseline. We will enable 5.10 by backporting upstream patches plus adding what we need on top.

**Comment by BaochengSu** [comment]
Sure, will plan to do refresh the queue next month!

**Review by BaochengSu — APPROVED** [review]

**Pull request merged**
