### PR TITLE
kernel:led:extend panic led state

### PR DESCRIPTION
**Pull request by AsuraZeng**
there is one LED state - blink when kernel panic occur
extend the panic led state to add ON and OFF.

It could customize more requirements.
Let the same type of trigger have different behaviors.

Signed-off-by: chao zeng <chao.zeng@siemens.com>

### CODE REVIEW

**Comment by AsuraZeng** [comment]
@jan-kiszka   pls help to review the extended panic led driver

**Comment by BaochengSu** [comment]
patch files look not identical with the files listed in bb file?

**Comment by jan-kiszka** [comment]
There is at least one redundant patch included.

More important is now clarifying the strategy with upstream.

**Comment by AsuraZeng** [comment]
@jan-kiszka  @BaochengSu  Have removed the redundant patches

And if no other problem,I would submit these patches to upstream and get some feedbacks from upstream

**Comment by jan-kiszka** [comment]
Upstream first, but that first patch is missing from here: The device tree binding extension.

**Comment by jan-kiszka** [comment]
What's the status here again?

**Comment by jan-kiszka** [comment]
Ping again, @AsuraZeng - rebase or close?

**Comment by AsuraZeng** [comment]
> Ping again, @AsuraZeng - rebase or close?

this is a long period story,   close it currently.

**Pull request closed without merging**
