### PR TITLE
sf:Query the write protect status before operating the device,

### PR DESCRIPTION
**Pull request by AsuraZeng**
and if not permit, return a prompt

When flash protect is enable,write or erase the flash would not reminder any error.
It would show "erase Ok",but actually erasing the flash is not success

Check the write protection status before operating the device

Signed-off-by: Chao Zeng <chao.zeng@siemens.com>

### CODE REVIEW

**Comment by jan-kiszka** [comment]
How does this relate to https://github.com/u-boot/u-boot/commit/b3b60f59124a1f4fdcee5b7eff3f057e33cfa4c7? If still needed despite of that, please submit upstream first before we merge here. Then also respect the coding style (see checkpatch.pl).

**Comment by AsuraZeng** [comment]
I have viewed this,and I think this PR(u-boot/u-boot@b3b60f5 ) is redundant  as  there already has a  function `flash_is_locked` to check the status.

**Comment by jan-kiszka** [comment]
So, backport the upstream change to our queue (which is 2021.04 based)?

**Comment by AsuraZeng** [comment]
I mean `u-boot/u-boot@b3b60f5 `is not necessary for UBOOT.
our change should submit to upstream I think.

**Comment by jan-kiszka** [comment]
I doubt that. But now you definitely should discuss requirements with upstream. Do you need a rebased tree over upstream master for that? I can update https://github.com/siemens/u-boot/commits/jan/iot2050 then.

**Review by jan-kiszka — CHANGES_REQUESTED** [review]
Resolve topic upstream first.

**Comment by AsuraZeng** [comment]
> I doubt that. But now you definitely should discuss requirements with upstream. Do you need a rebased tree over upstream master for that? I can update https://github.com/siemens/u-boot/commits/jan/iot2050 then.

I would put forward my different points of view to upstream to discuss it.

**Comment by jan-kiszka** [comment]
BTW, how to test this?

**Comment by AsuraZeng** [comment]
under uboot cli:
```
sf probe
sf protect lock 0 0x1000000
sf erase 0 0x1000000
```

**Comment by jan-kiszka** [comment]
What's the status here? Did you submit upstream? Any feedback?

**Comment by jan-kiszka** [comment]
@AsuraZeng ping...

**Comment by jan-kiszka** [comment]
Obsolete? Or just forgotten?

**Pull request closed without merging**
