### PR TITLE
Fixes for Ethernet driver

### PR DESCRIPTION
**Pull request by jan-kiszka**
Addresses one regression on PG1 and addresses some startup issues on PG2 devices.

### CODE REVIEW

**Review by BaochengSu — APPROVED** [review]

**Comment by rFond** [comment]
Hi @jan-kiszka,

I have recreate ti-pruss-firmware with last repos and command :
./kas-container build kas-iot2050-example.yml --target ti-pruss-firmware

I get ti-pruss-firmware_08.06.00.007_arm64.deb and I install package into my device with command :
sudo dpkg -i ti-pruss-firmware_08.06.00.007_arm64.deb
sudo reboot

And nothing I have already 1 CPU with zombie process.
What did i do wrong ?

**Comment by jan-kiszka** [comment]
For the 100% CPU load issue, you need a kernel update.

**Comment by rFond** [comment]
Why ?

**Comment by jan-kiszka** [comment]
Because you need https://github.com/siemens/meta-iot2050/blob/656743410587c58c12e43aee33a606f65c76afc9/recipes-kernel/linux/files/patches-5.10/0223-net-ethernet-ti-icssg_prueth-Initialize-emac-speed-o.patch.

**Comment by rFond** [comment]
Okay so I recreate kernel and install it on device ?

./kas-container build kas-iot2050-example.yml --target linux-iot2050

**Comment by jan-kiszka** [comment]
That should work for the example image, yes, not for SWUpdate images.

**Comment by rFond** [comment]
Okay it's working for me !
Thank's for your help !

**Pull request merged**
