### PR TITLE
Update iot2050_defconfig_extra.cfg

### PR DESCRIPTION
**Pull request by edu-sistec**
Enable Config_Wireguard in our kernel
Edu

### CODE REVIEW

**Comment by jan-kiszka** [comment]
Thanks for the contribution. A legal signed-off (DCO, see check) and a little bit of "why" in the commit message body is missing. See e.g. https://github.com/siemens/meta-iot2050/commit/45ecd8f9f11aabe05d7af2ce3948de6556226c8a#diff-fa4a7940524027b249597b2e38caf51db48c30997dcdeb1c22938a98793f21c1 which simply refers to the original issue (and closes that) as reason.

**Comment by edu-sistec** [comment]
Sorry,
I'm new here and I'm trying to understand what you've told me. I'm taking the wrong step.
Thanks for letting me know.
Edu

**Comment by BaochengSu** [comment]
Dear @edu-sistec , search for `DCO` within this page you would see the DCO check result marked as `X`, and by clicking the `Details` just right side of the DCO you would see the exact reason why your commit is failed to the DCO checking: you should add the `Signed-off-by: YOUR_NAME_HERE <YOUR_EMAIL_HERE>`.

Rembember this is not done by manually typing, instead by:
```bash
git commit --amend --no-edit --signoff
```

(Acutally this command already listed in the Details of the DCO).

Then normally the reason for the code change should be in the commit message, you could amend your commit message by:

```bash
git commit --amend
```

After doing these two things, you could use the `git push -f` to update this PR.

Thanks!

**Comment by edu-sistec** [comment]
Hello BaochengSu,

Sorry for this 'Pull Request', it was a misunderstanding, I really don't want to do this 'Pull Request', what I want is closed and deleted.
If you give me permission, I will.

Thanks for the information.
Edu

**Pull request closed without merging**
