### PR TITLE
integrate docker support

### PR DESCRIPTION
**Pull request by AsuraZeng**
For now,  I want to make the software configurable and optional. At present, the preinstalled software and some of our custom software have been made configurable

It's still a draft, Please help to review whether this approach is appropriate

### CODE REVIEW

**Comment by AsuraZeng** [comment]
@jan-kiszka @BaochengSu  
currently, this PR is ready for review.  pls help to review and add your comments.
thanks a lot

**Comment by AsuraZeng** [comment]
@jan-kiszka  hi jan.do you any comments on this PR?

**Comment by jan-kiszka** [comment]
Two things:
- We already do feature / package control in meta-iot2050. Why did you deviate from that pattern?
- Please provide some reasoning why each of those features should be controllable. It's obvious for heavy stuff like docker, but why controlling 32-bit support?
- IOT2050_DEBIAN_DEBUG_PACKAGES vs. IOT2050_BASIC_SOFTWARE_SUPPORT - does not sound like being the same thing.
- defaults differ in Kconfig vs. image recipe

**Comment by jan-kiszka** [comment]
The existing pattern is to have kas options fragment and select them in the kconfig. And there are also related entries in the menu that you didn't put into the same category now.

**Comment by AsuraZeng** [comment]
> 

if every item has correspond kas yml, the kas menu is just a front end of  build system.
if we'd like to control all the packages, there must many correspond yml files. 

Can kas menu be separated from kas yml ?
Selecting through the menu interface is more intuitive for some users
If we want to make software controllable, is there any elegant way?

**Comment by jan-kiszka** [comment]
Yes, this does not scale very well - and it relates to the discussion of what to make configurable **at all**. If you start adding a menu item for each possible package, kconfig will not scale either.

**Comment by AsuraZeng** [comment]
> 

@jan-kiszka  Has already refine this PR, pls help to review.

**Review by jan-kiszka — COMMENTED** [review]
Looks good, I would just call the option file docker.yml - shorter.

**Review by jan-kiszka — APPROVED** [review]

**Pull request merged**
