### PR TITLE
feat: enable soc device ID driver

### PR DESCRIPTION
**Pull request by AsuraZeng**
This allows Texas Instruments Keystone 3 SoCs to identify
specifics about the SoC in use

Signed-off-by: Chao Zeng <chao.zeng@siemens.com>

### CODE REVIEW

**Comment by jan-kiszka** [comment]
What use cases does this enable? I'd like to pick that up for upstream as well, just like to understand it first.

**Comment by AsuraZeng** [comment]
hi jan
this is enable `soc_device_match` function in the u-boot to distinguish sr1 or sr2 soc.

**Review by BaochengSu — APPROVED** [review]

**Comment by jan-kiszka** [comment]
Yes, but who is using this? Just a developer sitting in front of the U-Boot command line?

**Comment by BaochengSu** [comment]
> Yes, but who is using this? Just a developer sitting in front of the U-Boot command line?

function `omap_usb2_phy_probe` in `drivers/phy/omap-usb2-phy.c`, this enables a workaround for PG1.0 silicon bug regarding usb, see details in the comment below: 

```c
	/*
	 * AM654x PG1.0 has a silicon bug that D+ is pulled high after
	 * POR, which could cause enumeration failure with some USB hubs.
	 * Disabling the USB2_PHY Charger Detect function will put D+
	 * into the normal state.
	 *
	 * Enable this workaround for AM654x PG1.0.
	 */
	if (soc_device_match(am65x_sr10_soc_devices))
		priv->flags |= OMAP_USB2_DISABLE_CHG_DET;
```

**Comment by jan-kiszka** [comment]
OK, that makes it clear. Please write proper commit logs, always.

**Pull request merged**
